# -*- coding: utf-8 -*-
{
    "name" : "Orchid Cost Centre",
    "version" : "0.1",
    "author": "OrchidERP",
    "category" : "Accounting",
    "description": """OrchidERP Cost Centre management """,
    "website": ["http://www.orchiderp.com"],
    "depends": ['account','orchid_acc_voucher',
#        'point_of_sale',
'orchid_acc_report',
        'stock','orchid_cheque_management','orchid_product','account_asset','orchid_acc_filters'],
    "data" : [
    'security/orchid_cost_centre_security.xml',
#    'wizard/account_report_common_view.xml',
    'wizard/account_financial_report_view.xml',
	'wizard/od_trend_report_view.xml',
    'wizard/account_report_general_ledger_view.xml',
    'cost_centre_view.xml',
    'account_view.xml',
 #   'point_of_sale_view.xml',
    'report/account_entries_report_view.xml',
    'cheque_mangement_view.xml',
    'views/reconcile.xml',
    ],
    'css': [],
    'installable': True,
    'auto_install': False,
    'application': True,
} 
