# -*- coding: utf-8 -*-
{

	'name': 'Orchid Beta',
	'version': '1.0',
	'category': 'Production',
	'sequence':7,
	'summary': 'Orchid Beta',
	'author': 'OrchidERP',
	'website': 'https://orchiderp.com',
	'depends': ['base','purchase','orchid_hrms','orchid_payroll','sale','crm','account','orchid_product','orchid_hrms','orchid_asset','survey','orchid_labour_cost','orchid_wip','orchid_cost_sheet',],
	'data': [
			'security/ir.model.access.csv',
			'security/orchid_beta_security.xml',
            'hr/od_hr_late_time_seq.xml',
            'menu/accounting.xml',
            'menu/messaging.xml',
            'crm/mail_template.xml',
            'email/mail_templates.xml',
            'stock/stock_transfer_details.xml',
            'stock/grn_view.xml',
            'crm/crm_view.xml',
			'views/purchase_view.xml',
            'hr/report/od_hrms_salary_sheet_view_beta_view.xml',
            'hr/report/od_overtime_analysis_beta_view.xml',
            'hr/report/od_hrms_provision_beta_view.xml',
            'hr/hr_holidays_view.xml',
            'hr/hr_employee_view.xml',
            'hr/doc_request_view.xml',
            'hr/late_hour_view.xml',
            'hr/hr_payslip_view.xml',
			'account/account_invoice_view.xml',
			'account/res_currency_view.xml',
			
 			'sale/sale_workflow.xml',
 			'sale/sale_view.xml',
 			'views/stock_view.xml',
 			'product/product_view.xml',
 			'sale/res_partner_view.xml',
            'report/analytic_entry_report_view.xml',
            'report/pending_material_report_view.xml',
            'mis_report/mis_report.xml',
            'mis_report/product_sale_analysis.xml',
			],
	'demo': [],
	'test': [],
	'installable': True,
	'auto_install': False,
	'application': True,

}
