# -*- coding: utf-8 -*-
def od_task_vals():
    return [{'name': 'Preparation',
  'od_state': '1',
  'od_type': 'milestone',
  'val_id': '1',
  'amc':False,
  'val_parent_id': '0'},
 {'name': 'Receive Customer PO',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '2',
  'amc':False,
  'val_parent_id': '1'},
 {'name': 'Kick off Meeting',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '3',
  'amc':False,
  'val_parent_id': '1'},
 {'name': 'Conduct Site Survey',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '4',
  'amc':False,
  'val_parent_id': '1'},
 {'name': 'Confirm Site Readiness',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '5',
  'amc':False,
  'val_parent_id': '1'},
 {'name': 'Gathering Requirements',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '6',
  'amc':False,
  'val_parent_id': '1'},
 {'name': 'Approve Project Management Planning Documents',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '7',
  'amc':False,
  'val_parent_id': '1'},
 {'name': 'Materials Ordering',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '8',
  'amc':True,
  'val_parent_id': '1'},
 {'name': 'Design',
  'od_state': '4',
  'od_type': 'milestone',
  'val_id': '9',
  'amc':False,
  'val_parent_id': '0'},
 {'name': 'HLD',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '10',
  'amc':False,
  'val_parent_id': '9'},
 {'name': 'LLD',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '11',
  'amc':False,
  'val_parent_id': '9'},
 {'name': 'Prepare HLD Document',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '12',
  'amc':False,
  'val_parent_id': '10'},
 {'name': 'Submit HLD Document',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '13',
  'amc':False,
  'val_parent_id': '10'},
 {'name': 'Approve HLD Document',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '14',
  'amc':False,
  'val_parent_id': '10'},
 {'name': 'Prepare LLD Document',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '15',
  'amc':False,
  'val_parent_id': '11'},
 {'name': 'Submit LLD Document',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '16',
  'amc':False,
  'val_parent_id': '11'},
 {'name': 'Approve LLD Document',
  'od_state': '4',
  'od_type': 'workpackage',
  'val_id': '17',
  'amc':False,
  'val_parent_id': '11'},
 {'name': 'Implementation',
  'od_state': '5',
  'od_type': 'milestone',
  'val_id': '18',
  'amc':False,
  'val_parent_id': '0'},
 {'name': 'Materials Delivery',
  'od_state': '5',
  'od_type': 'workpackage',
  'val_id': '19',
  'amc':False,
  'val_parent_id': '18'},
 {'name': 'Technical Activities',
  'od_state': '5',
  'od_type': 'workpackage',
  'val_id': '20',
  'amc':False,
  'val_parent_id': '18'},
 {'name': 'Testing',
  'od_state': '11',
  'od_type': 'milestone',
  'val_id': '21',
  'amc':False,
  'val_parent_id': '0'},
 {'name': 'Testing and Fine Tuning',
  'od_state': '11',
  'od_type': 'workpackage',
  'val_id': '22',
  'amc':False,
  'val_parent_id': '21'},
 {'name': 'Knowledge Transfer',
  'od_state': '11',
  'od_type': 'workpackage',
  'val_id': '23',
  'amc':False,
  'val_parent_id': '21'},
 {'name': 'Close Out',
  'od_state': '7',
  'od_type': 'milestone',
  'val_id': '24',
  'amc':True,
  'val_parent_id': '0'},
 {'name': 'Prepare Final Documentation',
  'od_state': '7',
  'od_type': 'workpackage',
  'val_id': '25',
  'amc':False,
  'val_parent_id': '24'},
 {'name': 'Submit Final Documentation',
  'od_state': '7',
  'od_type': 'workpackage',
  'val_id': '26',
  'amc':False,
  'val_parent_id': '24'},
 {'name': 'Approve Final Documentation',
  'od_state': '7',
  'od_type': 'workpackage',
  'val_id': '27',
  'amc':False,
  'val_parent_id': '24'},


 {'name': 'Sign Closing Documents',
  'od_state': '7',
  'od_type': 'workpackage',
  'val_id': '28',
  'amc':True,
  'val_parent_id': '24'

  },
 {'name': 'Submit & Approve Customer Invoice',
  'od_state': '7',
  'od_type': 'workpackage',
  'val_id': '29',
  'amc':True,
  'val_parent_id': '24'},
 {'name': 'Preventive Maintenance',
  'od_state': '8',
  'od_type': 'milestone',
  'val_id': '30',
  'amc':True,
  'val_parent_id': '0'},
 {'name': 'Remedial Maintenance',
  'od_state': '8',
  'od_type': 'milestone',
  'val_id': '31',
  'amc':True,
  'val_parent_id': '0'},
 {'name': 'Operation',
  'od_state': '9',
  'od_type': 'milestone',
  'val_id': '32',
  'amc':True,
  'val_parent_id': '0'},
 {'name': 'Receive Materials From Suppliers',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '33',
  'amc':True,
  'val_parent_id': '8'},
 {'name': 'Deliver Materials to Customer',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '34',
  'amc':True,
  'val_parent_id': '8'},
 {'name': 'Materials Delivery Approval',
  'od_state': '1',
  'od_type': 'workpackage',
  'val_id': '35',
  'amc':True,
  'val_parent_id': '8'},
  {'name': 'RMA',
   'od_state': '8',
   'od_type': 'workpackage',
   'val_id': '36',
   'amc':True,
   'val_parent_id': '31'},
   {'name': 'TAC',
    'od_state': '8',
    'od_type': 'workpackage',
    'val_id': '37',
    'amc':True,
    'val_parent_id': '31'},


  ]
