# -*- coding: utf-8 -*-
{
    "name" : "Orchid HRMS",
    "version" : "0.1",
    "author": "OrchidERP",
    "category" : "Human Resources",
    "description": """Orchid HRMS """,
    "website": "http://www.orchiderp.com",
    "depends": ['base','hr_payroll','hr_holidays','hr_contract','hr','orchid_payroll','account_asset'],
    "data" : [
                'security/ir.model.access.csv',
            'security/orchid_asset_group.xml',
          
            'view/hr_view.xml',
            'view/od_hr_employee_benefits_view.xml',
            'view/od_air_route_view.xml',
            'view/od_employee_relation_view.xml',
            'view/od_employee_academic_qualification_view.xml',
            'view/od_employee_accomadation_view.xml',
            'view/od_employee_transportation_view.xml',
            'view/od_employee_document_type_view.xml',
            'view/od_employee_entitelment_view.xml',
            'view/od_document_request_view.xml',
            'view/od_document_return_view.xml',
            'view/od_employee_purpose_view.xml',
            'view/od_employee_joining_view.xml',
#            'view/res_company_view.xml',
            'view/od_on_hand_document_view.xml',
            'view/hr_salary_rule_view.xml',
            'view/hr_holiday_view.xml',
            'view/od_document_lines_tree_view.xml',
            'view/od_document_request_approval_view.xml',
            'view/od_employee_type_view.xml',
            'view/hr_holiday_status_view.xml',
            'report/od_hr_document_expiry_view.xml',
            'report/od_hr_document_history_final_view.xml',
            'wizard/od_leave_on_particular_period_report_wizard_view.xml',
            'view/od_leave_on_particular_period_report_view.xml',
            'menu_view.xml',
            'view/asset_transfer.xml',
            ],
    'css': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
